### ISSUE TITLE
Premature end of SSH session: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by glaslos** [johnnykv/heralding#28] opened 2017-01-06 12:58 UTC
Seeing quite a number of those:

```python
(heralding.capabilities.ssh) Premature end of SSH session: Error reading SSH protocol banner (67d3d676-16be-4052-9a72-7cc240735d8c)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/handlerbase.py", line 84, in handle_session
    self.execute_capability(address, gsocket, session)
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/ssh.py", line 48, in execute_capability
    SshWrapper(address, None, socket, session, self.options, self.key)
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/ssh.py", line 72, in __init__
    SSHHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/paramiko_ssh.py", line 66, in __init__
    BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 650, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/ssh.py", line 93, in setup
    self.transport.start_server(server=self)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 564, in start_server
    raise e
EOFError
<Greenlet at 0x7f89913c7b90: _handle_and_close_when_done(<bound method SSH.handle_session of <heralding.cap, <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f89913a7910 fileno=[Errno 9] Bad fi)> failed with EOFError```

**Comment by johnnykv** [comment] 2017-01-08 16:39
Duplicate of #21.

**Closed by johnnykv** 2017-01-08 16:39 UTC
