### ISSUE TITLE
RDP connection with Microsoft remote desktop tool result in error

### ISSUE THREAD

**Issue by t3chn0m4g3** [johnnykv/heralding#125] opened 2019-10-17 08:45 UTC
Using the latest master I am presented with the following error when trying to open a RDP connection:

```
heralding    | 2019-10-17 08:41:30,545 (asyncio) Task exception was never retrieved
heralding    | future: <Task finished coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.7/site-packages/heralding/capabilities/handlerbase.py:74> exception=IndexError('index out of range')>
heralding    | Traceback (most recent call last):
heralding    |   File "/usr/lib/python3.7/site-packages/heralding/capabilities/handlerbase.py", line 87, in handle_session
heralding    |     timeout=self.timeout, loop=self.loop)
heralding    |   File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
heralding    |     return fut.result()
heralding    |   File "/usr/lib/python3.7/site-packages/heralding/capabilities/rdp.py", line 57, in execute_capability
heralding    |     await self._handle_session(reader, writer, session)
heralding    |   File "/usr/lib/python3.7/site-packages/heralding/capabilities/rdp.py", line 66, in _handle_session
heralding    |     cr_pdu.parse(data)
heralding    |   File "/usr/lib/python3.7/site-packages/heralding/libs/msrdp/parser.py", line 155, in parse
heralding    |     self.cookie, pos = RawBytes(raw_data, None, None, pos).readUntil(b"\x0d\x0a")
heralding    |   File "/usr/lib/python3.7/site-packages/heralding/libs/msrdp/parser.py", line 74, in readUntil
heralding    |     i = _data[0]
heralding    | IndexError: index out of range
```

Other services, i.e. Telnet, SSH, VNC work without issues.

Please let me know how I can help.

**Comment by johnnykv** [comment] 2019-10-17 08:49
Which client do you connect with?

**Comment by t3chn0m4g3** [comment] 2019-10-17 08:51
For the purpose of the test I was using [MS RDP for Android](https://play.google.com/store/apps/details?id=com.microsoft.rdc.android&hl=de).

**Comment by t3chn0m4g3** [comment] 2019-10-17 08:54
Result for [MS RDP for macOS](https://apps.apple.com/de/app/microsoft-remote-desktop-10/id1295203466?mt=12) is the same error message within Heralding.
The MS RDP client error code is `0x4` (mac OS and Android).

**Comment by johnnykv** [comment] 2019-10-17 09:15
> Thanks for the feedback.
> 
> I reviewed the logs from the last 12 hours. It seems none of the rdp connections came through. If you like I can send you the JSON logs via Slack.

Yes, please do. Just for reference, can you verify that ._/hydra -l someuser -p somepass 127.0.0.1 rdp_ work against you honeypot?

**Comment by johnnykv** [comment] 2019-10-17 09:36
You need to compile hydra with RDP support 😀. Before compiling you need to
have freerdp2-dev installed.

**Comment by t3chn0m4g3** [comment] 2019-10-17 09:41
My Hydra is compiled with RDP support, works perfectly fine against my RDP server...
```
hydra -l someuser -p somepass rdp://myserver.home.local
Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-10-17 09:38:41
[WARNING] rdp servers often don't like many connections, use -t 1 or -t 4 to reduce the number of parallel connections and -W 1 or -W 3 to wait between connection to allow the server to recover
[INFO] Reduced number of tasks to 4 (rdp does not like many parallel connections)
[WARNING] the rdp module is experimental. Please test, report - and if possible, fix.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rdp://myserver.home.local:3389/
1 of 1 target completed, 0 valid passwords found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-10-17 09:38:41
```

**Comment by t3chn0m4g3** [comment] 2019-10-17 10:26
Made sure to use the correct version this time.

Hydra works against RDPY, but sadly not against Heralding. I can see my session coming in, but Hydra tells me the connection failed to establish:
```
2019-10-17 10:23:20.572282,0,564023a2-8130-42ae-a663-fef3d741568c,172.20.254.171,53692,88.150.249.82,3389,rdp,1
2019-10-17 10:23:20.648529,0,5fd11a3a-0838-456f-a305-24eb57241c86,172.20.254.171,53694,88.150.249.82,3389,rdp,1
2019-10-17 10:23:20.723169,0,bbb7255c-1276-404c-924f-ecf2fe03098e,172.20.254.171,53696,88.150.249.82,3389,rdp,1
2019-10-17 10:23:20.989253,0,2b0a896d-0f54-4362-9246-e0468d0fcd0b,172.20.254.171,53698,88.150.249.82,3389,rdp,1
```

**Comment by johnnykv** [comment] 2019-10-17 20:45
This but is confirmed with the Microsoft Remote Desktop app on IOS, Android and Macos.
To reproduce:
1. Install Remote desktop app
2. Try to login to Heralding from the app.

**Comment by realsdx** [comment] 2019-10-18 06:34
I am looking into it.

**Comment by realsdx** [comment] 2019-10-20 19:48
This particular Error is due to the fact that, the `x224ConnectionRequestPDU` function is not considering the "cookie" as optional parameter. My mistake! , can be easily fixed by just adding an if..else.
However, during the testing I am facing a new issue with Android client. I am still not sure what it is. I will update.

**Comment by t3chn0m4g3** [comment] 2019-10-21 18:07
@realsdx Thank you for the update!

**Comment by t3chn0m4g3** [comment] 2019-11-21 14:10
Do you have an update on this?

**Comment by realsdx** [comment] 2019-11-24 08:24
Not anything helpful.

**Comment by realsdx** [comment] 2019-11-24 08:26
After fixing that "cookie" problem, i encountered another issue of channel join request, where Android client abruptly closes the after sending the channel(1007) join confirm packet.

**Comment by t3chn0m4g3** [comment] 2019-11-25 08:14
@realsdx Thanks. Anything I can help you testing with?

**Comment by realsdx** [comment] 2019-11-25 08:17
I tested with two Android devices, same thing. If you can provide the packet capture and terminal out put that would be helpful.

**Comment by t3chn0m4g3** [comment] 2019-11-25 08:19
On the Heralding side?

**Comment by realsdx** [comment] 2019-11-25 19:13
> On the Heralding side?

Yes

**Comment by t3chn0m4g3** [comment] 2020-01-02 14:23
@realsdx What exactly do you need?

**Comment by t3chn0m4g3** [comment] 2020-01-02 17:18
With the Android client I get the error message `Error code: 0x4` and the following tcpdump:
```
tcpdump -vv -nn -i ens192 host 172.20.254.123
tcpdump: listening on ens192, link-type EN10MB (Ethernet), capture size 262144 bytes
17:16:36.336602 IP (tos 0x0, ttl 64, id 62316, offset 0, flags [DF], proto UDP (17), length 78)
    172.20.254.123.49935 > 255.255.255.255.137: [udp sum ok] UDP, length 50
17:16:36.336733 IP (tos 0x0, ttl 64, id 58314, offset 0, flags [DF], proto TCP (6), length 60)
    172.20.254.123.45876 > 172.20.254.130.3389: Flags [S], cksum 0xc7ac (correct), seq 133865233, win 65535, options [mss 1460,sackOK,TS val 2654479732 ecr 0,nop,wscale 9], length 0
17:16:36.336806 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    172.20.254.130.3389 > 172.20.254.123.45876: Flags [S.], cksum 0xb2d0 (correct), seq 3338194830, ack 133865234, win 65160, options [mss 1460,sackOK,TS val 2291726115 ecr 2654479732,nop,wscale 7], length 0
17:16:36.338037 IP (tos 0x0, ttl 64, id 58315, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.254.123.45876 > 172.20.254.130.3389: Flags [.], cksum 0xdf6e (correct), seq 1, ack 1, win 172, options [nop,nop,TS val 2654479743 ecr 2291726115], length 0
17:16:36.338759 IP (tos 0x0, ttl 64, id 58316, offset 0, flags [DF], proto TCP (6), length 71)
    172.20.254.123.45876 > 172.20.254.130.3389: Flags [P.], cksum 0xcd4b (correct), seq 1:20, ack 1, win 172, options [nop,nop,TS val 2654479744 ecr 2291726115], length 19
17:16:36.338793 IP (tos 0x0, ttl 63, id 45125, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.254.130.3389 > 172.20.254.123.45876: Flags [.], cksum 0xde07 (correct), seq 1, ack 20, win 509, options [nop,nop,TS val 2291726117 ecr 2654479744], length 0
17:16:36.339830 IP (tos 0x0, ttl 63, id 45126, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.254.130.3389 > 172.20.254.123.45876: Flags [F.], cksum 0xde05 (correct), seq 1, ack 20, win 509, options [nop,nop,TS val 2291726118 ecr 2654479744], length 0
17:16:36.340697 IP (tos 0x0, ttl 64, id 58317, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.254.123.45876 > 172.20.254.130.3389: Flags [F.], cksum 0xdf53 (correct), seq 20, ack 2, win 172, options [nop,nop,TS val 2654479746 ecr 2291726118], length 0
17:16:36.340738 IP (tos 0x0, ttl 63, id 45127, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.254.130.3389 > 172.20.254.123.45876: Flags [.], cksum 0xde01 (correct), seq 2, ack 21, win 509, options [nop,nop,TS val 2291726119 ecr 2654479746], length 0
```

**Comment by MxRay** [comment] 2020-01-31 07:35
Unfortunately, I can confirm the same behavior with plain Windows Remote Desktop Connection client.

**Comment by realsdx** [comment] 2020-01-31 20:37
Which version of windows? and RDP client version?

**Comment by ariadarkkkis** [comment] 2020-02-04 00:55
I have same issue 
![heraldingrdperror](https://user-images.githubusercontent.com/25063830/73703775-56365a80-4706-11ea-89cd-a5f4acbdcc16.jpg)

**Comment by MxRay** [comment] 2020-02-04 08:59
> Which version of windows? and RDP client version?

Here you go:

![image](https://user-images.githubusercontent.com/9169152/73729143-c9ef5c00-4734-11ea-9585-f3796fb3474a.png)
![image](https://user-images.githubusercontent.com/9169152/73729237-f4411980-4734-11ea-8702-2ac9dfd9f84e.png)

**Comment by ariadarkkkis** [comment] 2020-02-25 20:59
Any updates on this issue?
Heralding works like a charm on Linux using as SSH Honeypot. Still need some tweaks to make it more legit but its working good. thanks

**Comment by t3chn0m4g3** [comment] 2020-02-26 08:42
@realsdx Do you have an update on this issue? Are the provided info sufficient for debugging?

**Comment by realsdx** [comment] 2020-02-26 09:03
> After fixing that "cookie" problem, i encountered another issue of channel join request, where Android client abruptly closes the after sending the channel(1007) join confirm packet.

I will send a PR fixing this, but even after this there is still a problem with the Android client.

**Comment by t3chn0m4g3** [comment] 2020-02-26 09:05
@realsdx Thanks for the feedback and your work on this!

**Comment by johnnykv** [comment] 2020-02-26 16:15
#132

**Comment by johnnykv** [comment] 2020-03-01 12:33
A fix from @realsdx dx was just merged into master. Please note, that currently Heralding only support RDP when supplying credentials beforehand, ie. if you use the microsoft RDP client, you need to fill in username and password before connecting.

The other scenario, where a user connects and is presented with a login screen and enters the login info "remotely" if not supported currently.

**Closed by johnnykv** 2020-03-01 12:33 UTC
Labels: bug

**Comment by t3chn0m4g3** [comment] 2020-03-02 15:21
Thanks guys, the error does not show up anymore. However I can see that the credentials are being cut off in `auth.csv`:
```
timestamp,auth_id,session_id,source_ip,source_port,destination_ip,destination_port,protocol,username,password,password_hash
2020-03-02 15:15:17.744846,bfb5bf9e-2b98-4b1d-bf61-9069e7fcefa4,7306eb48-151c-4a0c-bf30-af7e700282a0,172.20.254.111,50812,1.2.3.4,3389,rdp,tes,tes,
2020-03-02 15:16:45.958697,27dcafae-788b-4f09-a987-37ef7d9dcf19,1db21b5f-40d1-4306-baeb-fb12d3605bcb,172.20.254.111,50818,1.2.3.4,3389,rdp,joh,do,
```
First entry should be `test,test`, second entry should be `john,doe`

**Comment by johnnykv** [comment] 2020-03-02 15:58
> Thanks guys, the error does not show up anymore. However I can see that the credentials are being cut off in `auth.csv`:
> 
> ```
> timestamp,auth_id,session_id,source_ip,source_port,destination_ip,destination_port,protocol,username,password,password_hash
> 2020-03-02 15:15:17.744846,bfb5bf9e-2b98-4b1d-bf61-9069e7fcefa4,7306eb48-151c-4a0c-bf30-af7e700282a0,172.20.254.111,50812,1.2.3.4,3389,rdp,tes,tes,
> 2020-03-02 15:16:45.958697,27dcafae-788b-4f09-a987-37ef7d9dcf19,1db21b5f-40d1-4306-baeb-fb12d3605bcb,172.20.254.111,50818,1.2.3.4,3389,rdp,joh,do,
> ```
> 
> First entry should be `test,test`, second entry should be `john,doe`

Nice find, opened new issue.

**Comment by t3chn0m4g3** [comment] 2020-03-02 15:59
Thank you 😄
