### ISSUE TITLE
vnc not logging passwords

### ISSUE THREAD

**Issue by rewthing** [johnnykv/heralding#122] opened 2019-09-10 11:38 UTC
I'm running Heralding version 1.0.5 on Python 3.7 (Kali Rolling), installed via pip3.  Unusual destination port below is due to nftables redirect rule.  All the other modules seem to work fine but VNC shows lines like this in log_auth.csv:

    2019-09-09 19:10:23.936595,35fdd8fe-7cde-4830-bf75-1705fff5bc20,a4b8ce74-468c-48bc-8a67-461baa4c0958,157.245.161.153,36822,24.118.x.x,8611,vnc,,
    2019-09-09 19:10:23.937029,5167c500-2fed-42d4-863e-cf8d1f1a30d9,c93ca4f4-4df2-456f-b720-62138768aabd,157.245.161.153,36820,24.118.x.x,8611,vnc,,
    2019-09-09 19:10:24.237219,a427c3ab-4a19-42c1-81b9-02bb907aba78,37e80146-8204-44fe-b1e8-17f3470baf59,157.245.161.153,37210,24.118.x.x,8611,vnc,,
    2019-09-09 19:10:24.240026,eb861294-1600-4470-b28a-03d0ca57baba,7fe87471-1bd2-429a-9a4d-2b51cf9ad5b9,157.245.161.153,37208,24.118.x.x,8611,vnc,,

I don't know Python, so I'm not sure where to start troubleshooting.  Suggestions welcome...

**Comment by realsdx** [comment] 2019-09-10 11:50
VNC, protocol doesn't use any username for authentication so that part will be empty always.
As, vnc protocol uses 'DES' encryption to encrypt passwords you won't get them either on Heralding version 1.0.5. But, the current git version has a hash cracker(dictionary based) for the VNC protocol. Try that.

**Comment by rewthing** [comment] 2019-09-11 12:37
Sweet.  I'll try that when I get a chance.

I did look at vnc.py ... Would it speed things up to use a fixed challenge there instead of urandom?

**Comment by realsdx** [comment] 2019-09-18 10:42
Yes , it will speed things up. But, that would make it easily fingerprintable.

**Comment by johnnykv** [comment] 2019-10-11 18:56
Closing this, since it's not a bug.  Somewhere down the road we would like to add some kind of adaptive wordlist feature. Sort of, updating the wordlist as we go using passwords collected from the other protocols.

**Closed by johnnykv** 2019-10-11 18:56 UTC
